sudo: required
language: python
services:
  - docker
python: 3.6
install: pip install -r requirements/test
script: pytest
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
      docker build -t bitelio/worker .;
      docker push bitelio/worker;
    fi
