boards:
  indices: [Id]
  unique: [Id]
card_types:
  indices: [Id, BoardId]
  unique: [Id]
cards:
  indices: [Id, BoardId]
  unique: [Id]
classes_of_service:
  indices: [Id, BoardId]
  unique: [Id]
events:
  indices: [BoardId, CardId]
  unique: []
lanes:
  indices: [Id, BoardId]
  unique: [Id]
users:
  indices: [Id, BoardId]
  unique: []
settings:
  indices: [Id]
  unique: [Id]
