version: 1
disable_existing_loggers: False

formatters:
  default:
    style: "{"
    format: "{asctime} │ {levelname:<7} │ {message}"
  simple:
    format: "%(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: default
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default
    filename: worker.log
    maxBytes: 10485760
    backupCount: 3
    encoding: utf8

loggers:
  worker:
    level: DEBUG
    handlers: [console, file]
    propagate: False
  leankit:
    level: DEBUG
    handlers: [console]
    propagate: False

root:
  level: INFO
  handlers: [console]
